move to Ferrum for screenshots

diff --git a/bin/export b/bin/export
--- a/bin/export
+++ b/bin/export
@@ -23,9 +23,14 @@ set -vx
 # - GNU parallel
 # - curl
 
-if ! [ -x "$(command -v http)" ]
-then
-	echo "Couldn't find HTTPie, which is required to proceed."
+if ! command -v aws || curl || exiftool || parallel || http; then
+	echo "Couldn't find all required software. Needed to proceed:"
+	echo
+	echo "AWS CLI"
+	echo "curl"
+	echo "exiftool"
+	echo "GNU parallel"
+	echo "HTTPie"
 	exit 1
 fi
 
@@ -44,28 +49,28 @@ then
 	$SCROLLY/bin/rails runner ./step_1_build_index/published_entries.rb $cname
 fi
 
-# STEP: download index.html to story folders.
+# STEP: download live index.html to story folders.
 bin/20_canonical_urls.rb $cname \
-	| parallel http --ignore-stdin --timeout 60 --download --output $dest/{/}/original.html GET {}
+	| parallel --jobs 5 http --ignore-stdin --timeout 60 --download --output $dest/{/}/original.html GET {}
 
 # and the story-specific CSS
 bin/20_canonical_urls.rb $cname \
-  | parallel http --ignore-stdin --timeout 60 GET https://$cname/entries/{/}.css \
+  | parallel --jobs 5 http --ignore-stdin --timeout 60 GET https://$cname/entries/{/}.css \
 	"|"ruby ./step_2_download_story/replace.rb ">"$dest/entries/{/}.css
 
 # STEP: massage the HTML until it's fit for archiving.
-parallel ruby ./step_2_download_story/replace.rb \
+parallel --jobs 5 ruby ./step_2_download_story/replace.rb \
 	"<"{} ">"{//}/index.html ::: $dest/*/original.html
 
 # STEP: sync media bucket
 #   add --dryrun before the last quote to see what it will do
 ./step_3_sync_assets/media_folders $cname \
-	| parallel "aws s3 sync s3://{} ${dest}/{}"
+	| parallel --jobs 1 "aws --profile scrollytelling s3 sync s3://{} ${dest}/{}"
 
 # STEP: sync output bucket. Bucket name is different from local path.
 #   add --dryrun before the last quote to see what it will do
 ./step_3_sync_assets/output_folders $cname \
-	| parallel "aws s3 sync s3://storyboard-pageflow-production-out{} \
+	| parallel --jobs 1 "aws --profile scrollytelling s3 sync s3://storyboard-pageflow-production-out{} \
 	${dest}/output.scrollytelling.com{}"
 
 # STEP: unpack static assets.
@@ -79,15 +84,15 @@ unzip -u ./artifacts/root.zip -d $dest
 # Convert the PNGs to JPGs
 if [ -x "$(command -v vips)" ]
 then
-	parallel vips jpegsave {} {.}.jpg ::: ${dest}/**/screenshots/*.png
+	parallel --jobs 10 vips jpegsave {} {.}.jpg ::: ${dest}/**/screenshots/*.png
 	vipsthumbnail ${dest}/**/screenshots/*.png --format=%s_280.jpg --size=280
 fi
 
 # STEP: Generate checksums, to verify archive authenticity.
 cd $dest
 rm --force SHA512SUMS
-find -name '*.html' -type f | parallel "sha512sum --text {} >>SHA512SUMS"
-find media.scrollytelling.com -path '*/original/*' -type f | parallel "sha512sum --binary {} >>SHA512SUMS"
+find -name '*.html' -type f | parallel --jobs 10 "sha512sum --text {} >>SHA512SUMS"
+find media.scrollytelling.com -path '*/original/*' -type f | parallel --jobs 10 "sha512sum --binary {} >>SHA512SUMS"
 cd -
 
 # STEP: compile templates based on exported information.
